@@startuml

activate GameController
GameController -> GameController : Run()
loop _running == true
    GameController -> GameController : Check turn order, Monster1 turn
    
    GameController -> Monster1 : Get attack value
    activate Monster1
    return attack 
    UI <- GameController : Display "{name} attacks!"
    GameController -> Monster2 :  OnTakeDamage(dmg)
    activate Monster2
    return dmg taken
    UI <- GameController : Display damage taken, update ui
    
    alt Enemy is dead
        GameController -> UI : Update defeated monster count
        GameController -> MonsterController : SpawnMonster()
        activate MonsterController
        MonsterController -> MonsterController : Build new monster
        return new monster
    end
    alt Player is dead
        GameController -> UI : Display game over
        GameController -> GameController : _running = false
    end
end
@@enduml
